services:
  quality-lab-pro-front-end:
    restart: always
    image: leonardomeireles55/quality-lab-pro-front-end:latest
    ports:
      - '3000'
    environment:
      - NODE_ENV=production
    volumes:
      - qualitylab_public:/app/.next/standalone/public
      - qualitylab_static:/app/.next/standalone/.next/static
      - qualitylab_standalone:/app/.next/standalone

    stdin_open: true
    tty: true
    # command: ['npm', 'start']
    command: ['node', '.next/standalone/server.js']
    networks:
      - qualitylab-net

volumes:
  qualitylab_node_modules:
  qualitylab_static:
  qualitylab_public:
  qualitylab_standalone:

networks:
  qualitylab-net:
    driver: bridge
    name: qualitylab-net
