services:
    quality-lab-pro-front-end:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000'
        environment:
            - NODE_ENV=production
        volumes:
            # - qualitylab_node_modules:/app/node_modules
            - qualitylab_public:/app/public
        stdin_open: true
        tty: true
        command: ['npm', 'start']
        networks:
            - qualitylab-net

volumes:
    qualitylab_node_modules:
    qualitylab_public:

networks:
    qualitylab-net:
        external: true
