services:
  quality-lab-pro-front-end:
    restart: always
    image: leonardomeireles55/quality-lab-pro-front-end:latest
    ports:
      - '3000'
    environment:
      - NODE_ENV=production
    command: ['node', './server.js']
    networks:
      - qualitylab-net
networks:
  qualitylab-net:
    driver: bridge
    name: qualitylab-net
