name: Frontend Deploy Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: [self-hosted, linux, x64, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          docker compose -f docker-compose.build.yml build
          docker compose -f docker-compose.build.yml push

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64, frontend]
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy application
        run: |
          docker compose pull
          docker compose up -d

      - name: Deployment notification
        run: echo "✅ Deployment completed"

  health-check:
    needs: deploy
    runs-on: [self-hosted, linux, x64, frontend]
    steps:
      - name: Verify application health
        run: |
          # Initial wait for application startup
          sleep 15

          CONTAINER_NAME="labgraph-front-end-quality-lab-pro-front-end-1"

          # Check if container is running and healthy
          if ! docker container inspect $CONTAINER_NAME --format '{{.State.Status}}' | grep -q "running"; then
            echo "❌ Container $CONTAINER_NAME is not running properly"
            docker logs $CONTAINER_NAME --tail 50
            exit 1
          fi

          # Use container's network namespace for health check
          HEALTH_CHECK_URL="http://labgraph-front-end-quality-lab-pro-front-end-1:3000/api/health-check"
          MAX_RETRIES=5
          COUNT=0

          while [ $COUNT -lt $MAX_RETRIES ]; do
            if docker exec $CONTAINER_NAME curl -s -f $HEALTH_CHECK_URL; then
              echo "🟢 Application is healthy!"
              exit 0
            fi
            COUNT=$((COUNT + 1))
            echo "Health check attempt $COUNT failed. Retrying..."
            sleep 10
          done

          # If we get here, health check failed
          echo "❌ Application failed health check"
          docker logs $CONTAINER_NAME --tail 50
          exit 1

      - name: Final status
        if: success()
        run: echo "🚀 Application is running successfully in production"
