name: Frontend Deploy Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: [self-hosted, linux, x64, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          docker compose -f docker-compose.build.yml build
          docker compose -f docker-compose.build.yml push

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64, frontend]
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy application
        run: |
          docker compose pull
          docker compose up -d

      - name: Deployment notification
        run: echo "✅ Deployment completed"

 health-check:
    runs-on: [ self-hosted, linux, x64, backend ]
    needs: deploy
    timeout-minutes: 5
    steps:
      - name: Health check with timeout and retry
        run: |
          max_attempts=12
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            if curl -sSf https://lab-spec.systems/api/health-check; then
              echo "✅ Service is healthy!"
              exit 0
            fi
            echo "Attempt $attempt/$max_attempts - Service not healthy yet..."
            sleep 15
            attempt=$((attempt + 1))
          done
          echo "Health check failed after $max_attempts attempts"
          exit 1

      - name: Final status
        if: success()
        run: echo "🚀 Application is running successfully in production"
