name: Frontend Deploy Pipeline

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64, frontend]
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure buildx cache directory
        run: mkdir -p /tmp/.buildx-cache

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: leonardomeireles55/quality-lab-pro-front-end:latest
          cache-from: type=registry,ref=leonardomeireles55/quality-lab-pro-front-end:latest
          cache-to: type=inline,mode=min

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64, frontend]
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy application
        run: |
          docker compose pull
          docker compose up -d

      - name: Deployment notification
        run: echo "✅ Deployment completed"

  health-check:
    runs-on: [self-hosted, linux, x64, backend]
    needs: deploy
    timeout-minutes: 5
    steps:
      - name: Health check with timeout and retry
        run: |
          max_attempts=12
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            if curl -sSf https://lab-spec.systems/api/health-check; then
              echo "✅ Service is healthy!"
              exit 0
            fi
            echo "Attempt $attempt/$max_attempts - Service not healthy yet..."
            sleep 15
            attempt=$((attempt + 1))
          done
          echo "Health check failed after $max_attempts attempts"
          exit 1

      - name: Final status
        if: success()
        run: echo "🚀 Application is running successfully in production"
